# Generated by Django 4.0.4 on 2022-05-15 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlikes',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='userlikes',
            old_name='user_id',
            new_name='user',
        ),
    ]
