# Generated by Django 3.2.6 on 2022-07-15 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220715_2235'),
        ('posts', '0002_auto_20220715_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='post_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='posts.posts'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.users'),
        ),
        migrations.AlterField(
            model_name='userlikes',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='posts.posts'),
        ),
        migrations.AlterField(
            model_name='userlikes',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.users'),
        ),
    ]
