# Generated by Django 3.2.6 on 2022-05-18 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=500, null=True)),
                ('token', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('is_admin', models.BooleanField(blank=True, null=True)),
                ('sms_code', models.CharField(blank=True, max_length=4, null=True)),
                ('is_phone_confirmed', models.BooleanField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.IntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserSubscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_subscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subscriber', to='users.users')),
                ('user_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subscription', to='users.users')),
            ],
            options={
                'db_table': 'usersubscriptions',
                'managed': True,
            },
        ),
    ]
