# Generated by Django 4.0.4 on 2022-06-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodePhones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('sms_code', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'db_table': 'codes',
                'managed': True,
            },
        ),
    ]
