# Generated by Django 3.2.6 on 2022-06-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_codephones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
