# Generated by Django 3.2.6 on 2022-07-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
