# Generated by Django 3.2.6 on 2022-07-15 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220715_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usersubscriptions',
            name='user_subscriber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subscriber', to='users.users'),
        ),
        migrations.AlterField(
            model_name='usersubscriptions',
            name='user_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subscription', to='users.users'),
        ),
    ]
