# Generated by Django 3.2.6 on 2022-07-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_users_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_view_notification',
            field=models.BooleanField(default=False),
        ),
    ]
