# Generated by Django 3.2.6 on 2022-08-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_users_is_view_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='registration_timestamp',
            field=models.IntegerField(default=1660154898.5395956),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_view_notification',
            field=models.BooleanField(default=True),
        ),
    ]
