# Generated by Django 4.0.4 on 2022-05-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='media_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
