# Generated by Django 4.0.4 on 2022-05-17 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_stories_media_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stories',
            name='media_type',
        ),
    ]
