# Generated by Django 4.0.4 on 2022-05-17 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_users_birthday_users_timestamp'),
        ('stories', '0003_remove_stories_media_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlikesstories',
            old_name='post',
            new_name='liked_story',
        ),
        migrations.RenameField(
            model_name='userlikesstories',
            old_name='user',
            new_name='liked_user',
        ),
        migrations.CreateModel(
            name='UserViewStories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stories.stories')),
                ('viewed_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.users')),
            ],
            options={
                'db_table': 'userviewsstories',
                'managed': True,
            },
        ),
    ]
