# Generated by Django 4.0.4 on 2022-05-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('user_id', models.PositiveIntegerField(blank=True, max_length=100, null=True)),
                ('count_of_likes', models.PositiveIntegerField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'posts',
                'managed': True,
            },
        ),
    ]
